// Writes sw.js into the web export: it caches every file of this build so the app opens offline,
// and replaces the old build's cache when a new one is published.
// Usage: node scripts/web-sw.mjs <export dir> [base path]
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const out = process.argv[2];
const base = process.argv[3] ?? '/metakai/app';
if (!out) throw new Error('Usage: node scripts/web-sw.mjs <export dir> [base path]');

const files = [];
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) walk(path);
    else files.push(relative(out, path).split('\\').join('/'));
  }
})(out);

const assets = files.filter((f) => f !== 'sw.js' && f !== '404.html' && !f.endsWith('.map')).sort();
const hash = createHash('sha256');
for (const f of assets) hash.update(f).update(readFileSync(join(out, f)));
const version = hash.digest('hex').slice(0, 12);
const urls = assets.map((f) => `${base}/${f === 'index.html' ? '' : f}`);

const sw = `// Generated by scripts/web-sw.mjs. Caches this build of the Metakai web app for offline use.
const BASE = ${JSON.stringify(base)};
const CACHE = 'metakai-${version}';
const FILES = ${JSON.stringify(urls, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('metakai-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin || !url.pathname.startsWith(BASE + '/')) return;
  if (req.mode === 'navigate') {
    // Every screen is the same app shell, so the cached page opens instantly, offline too.
    event.respondWith(caches.match(BASE + '/').then((cached) => cached || fetch(req)));
    return;
  }
  event.respondWith(caches.match(req).then((cached) => cached || fetch(req)));
});
`;
writeFileSync(join(out, 'sw.js'), sw);
console.log(`sw.js: ${urls.length} files, cache metakai-${version}`);
